import { conversion, logger } from "@utils";
import fs from "fs";
import path from "path";
import { lightSeederStub } from "../../stubs";

// =================================>
// ## Command: Blueprint seeder generation
// =================================>
export async function seederGeneration(
  model: string,
  schema: Record<string, string> = {},
  data: any[][] = [],
  marker: string
): Promise<boolean> {
  const modelName = conversion.strPascal(model?.split("/")?.pop() || "");
  const name = modelName + "Seeder";
  const basePath = path.join(process.cwd(), "src", "database", "seeders");
  const filename = conversion.strSlug(modelName);
  const filePath = path.join(basePath, `${filename}.seeder.ts`);
  
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, "utf-8");

    if (!content.includes("AUTO-GENERATED BY BLUEPRINT")) {
      logger.info(`Skip overridden file: ${filePath}`);
      return false;
    }
  }

  const schemaKeys = Object.keys(schema);

  const seeders = data.map((row) =>
    `  {${row
      .map((val, idx) => {
        const col = schemaKeys[idx];
        return `"${col}": ${isNaN(val as any) ? `"${val}"` : val}`;
      })
    .join(", ")}}`).join(",\n    ");

  let stub = lightSeederStub;

  stub = stub
    .replace(/{{\s*marker\s*}}/g, marker)
    .replace(/{{\s*name\s*}}/g, name)
    .replace(/{{\s*model\s*}}/g, modelName)
    .replace(/{{\s*seeders\s*}}/g, seeders);

  if (!fs.existsSync(basePath)) {
    fs.mkdirSync(basePath, { recursive: true });
  }

  fs.writeFileSync(filePath, stub, "utf-8");

  return true;
}
